#Head
Fighters_Mask1 = {"Name": "Fighter's Mask +1", "DEF":28, "HP":15, "DEX":5, "VIT":5, "Enmity":1, "HHP":1, "Crit Rate":3, "Gear Haste":5, "Jobs":["war"]}
Temple_Crown1 = {"Name": "Temple Crown +1", "DEF":23, "HP":16, "MND":8, "Focus":10, "HPP":1, "Crit Rate":3, "Gear Haste":5, "Jobs":["mnk"]}
Healers_Cap1 = {"Name": "Healers Cap +1", "DEF":21, "MP":28, "MND":7, "Enmity":-1, "HMP":4, "Refresh":1, "Jobs":["whm"]}
Wizards_Petasos1 = {"Name": "Wizards Petasos +1", "DEF":20, "MP":30, "INT":5, "Enmity":-4, "HMP":4, "Refresh":1, "Jobs":["blm"]}
Warlocks_Chapeau1 = {"Name": "Warlocks Chapeau +1", "DEF":24, "MP":25, "INT":5, "Elemental Magic Skill":10, "FC":10, "Magic Attack Bonus":6, "Conserve MP":5, "Jobs":["rdm"]}
Rogues_Bonnet1 = {"Name": "Rogues Bonnet +1", "DEF":24, "HP":13, "DEX":3, "Ranged Accuracy":8, "Evasion":8, "Gear Haste":5, "Crit Rate":3, "Jobs":["thf"]}
Gallant_Coronet1 = {"Name": "Gallant Coronet +1", "DEF":28, "HP":12, "MND":6, "Enmity":3, "DT":-3, "Cure Received":5, "Jobs":["pld"]}
Chaos_Burgeonet1 = {"Name": "Chaos Burgeonet +1", "DEF":27, "HP":12, "MP":12, "STR":7, "Dark Magic Skill":5, "Souleater":2, "Crit Rate":3, "Gear Haste":5, "Jobs":["drk"]}
Beast_Helm1 = {"Name": "Beast Helm +1", "DEF":26, "HP":15, "INT":8, "MND":8, "Charm":4, "Pet Haste":5, "Gear Haste":5, "Jobs":["bst"]}
Choral_Roundlet1 = {"Name": "Choral Roundlets +1", "DEF":19, "HP":11, "MND":6, "CHR":6, "Parrying Skill":5, "Enmity":-2, "Refresh":1, "Regen":3, "Jobs":["brd"]}
Hunters_Beret1 = {"Name": "Hunters Beret +1", "DEF":24, "HP":13, "AGI":4, "INT":4, "Ranged Attack":5, "Rapid Shot":4, "Ranged Accuracy":5, "Jobs":["rng"]}
Myochin_Kabuto1 = {"Name": "Myochin Kabuto +1", "DEF":25, "HP":13, "STR":5, "MND":5, "Warding Circle":2, "Meditate Duration":4, "Crit Rate":3, "Gear Haste":5, "Jobs":["sam"]}
Ninja_Hatsuburi1 = {"Name": "Ninja Hatsuburi +1", "DEF":22, "HP":10, "AGI":8, "CHR":8, "Evasion":8, "Ninjutsu Skill":5, "Crit Rate":3, "Gear Haste":5, "Jobs":["nin"]}
Drachen_Armet1 = {"Name": "Drachen Armet +1", "DEF":25, "HP":12, "VIT":8, "MND":8, "Spirit Link":10, "Crit Rate":3, "Gear Haste":5, "Jobs":["drg"]}
Evokers_Horn1 = {"Name": "Evokers Horn +1", "DEF":15, "MP":25, "INT":6, "MND":6, "Summoning Magic Skill":5, "Refresh":1, "HMP":4, "Jobs":["smn"]}
Magus_Keffiyeh1 = {"Name": "Magus Keffiyeh +1", "DEF":24, "MP":25, "INT":5, "MND":5, "Monster Correlation":2, "Crit Rate":3, "Gear Haste":5, "Jobs":["blu"]}
Corsairs_Tricorne1 = {"Name": "Corsairs Tricorne +1", "DEF":23, "HP":13, "STR":4, "AGI":4, "Ranged Accuracy":9, "Quick Draw":10, "Ranged Attack":6, "Regen":2, "Jobs":["cor"]}
Puppetry_Taj1 = {"Name": "Puppetry Taj +1", "DEF":16, "HP":15, "DEX":5, "VIT":5, "MND":5, "Automaton HHP":3, "Automaton HMP":3, "Pet Haste":5, "Gear Haste":5, "Jobs":["pup"]}
Dancers_Tiara1 = {"Name": "Dancers Tiara +1", "DEF":19, "HP":15, "DEX":4, "CHR":4, "Enmity":-2, "Samba Duration":30, "Crit Rate":3, "Gear Haste":5, "Jobs":["dnc"]}
Scholars_Motarboard1 = {"Name": "Scholars Motarboard +1", "DEF":16, "MP":20, "INT":5, "Sublimation":1, "Enmity":-1, "Magic Burst Damage":3, "Magic Attack Bonus":5, "Jobs":["sch"]}
Geomancy_Galero1 = {"Name": "Geomancy Galero +1", "DEF":25, "MP":25, "INT":5, "Elemental Magic Skill":15, "Refresh":1, "Conserve MP":5, "Jobs":["geo"]}
Runeist_Bandeau1 = {"Name": "Runeist Bandeau +1", "DEF":27, "HP":27, "DEX":5, "PDT":-3, "Regen Duration":3, "Enmity":5, "Regen":2, "Jobs":["run"]}

#Body
Fighters_Lorica1 = {"Name": "Fighters Lorica +1", "DEF":50, "HP":20, "VIT":7, "Attack":10, "Enmity":14, "PDT":-3, "Jobs":["war"]}
Temple_Cyclas1 = {"Name": "Temple Cyclas +1", "DEF":44, "HP":20, "STR":6, "VIT":6, "Accuracy":6, "Martial Arts":2, "Store TP":5, "Jobs":["mnk"]}
Healers_Bliaut1 = {"Name": "Healers Bliaut +1", "DEF":40, "MP":53, "Enfeebling Magic Skill":12, "Enmity":-4, "HMP":5, "DT":-5, "Jobs":["whm"]}
Wizards_Coat1 = {"Name": "Wizards Coat +1", "DEF":38, "MP":54, "Enfeebling Magic Skill":12, "Enmity":-5, "HMP":5, "Magic Accuracy":5, "Jobs":["blm"]}
Warlocks_Tabard1 = {"Name": "Warlocks Tabard +1", "DEF":44, "MP":55, "Spell Interrupt Rate Down":12, "Enfeebling Magic Skill":15, "HMP":5, "Magic Accuracy":5, "Jobs":["rdm"]}
Rogues_Vest1 = {"Name": "Rogues Vest +1", "DEF":45, "HP":20, "STR":6, "Accuracy":10, "Dual Wield":3, "Regen":2, "Jobs":["thf"]}
Gallant_Surcoat1 = {"Name": "Gallant Surcoat +1", "DEF":55, "HP":20, "VIT":6, "Divine Magic Skill":8, "Enmity":2, "Refresh":1, "Block Rate":3, "Jobs":["pld"]}
Chaos_Cuirass1 = {"Name": "Chaos Cuirass +1", "DEF":49, "HP":20, "MP":20, "STR":7, "VIT":7, "Attack":10, "Enfeebling Magic Skill":5, "Refresh":1, "Regen":3, "Jobs":["drk"]}
Beast_Jackcoat1 = {"Name": "beast Jackcoat +1", "DEF":49, "HP":20, "VIT":6, "Charm":6, "Enhances Reward":1, "Pet DT":-5, "Gear Haste":3, "Jobs":["bst"]}
Choral_Justacorps1 = {"Name": "Choral Justacoprs +1", "DEF":45, "HP":20, "VIT":10, "CHR":10, "String Skill":6, "Enmity":-3, "Singing Skill":5, "Wind Skill":6, "Jobs":["brd"]}
Hunters_Jerkin1 = {"Name": "Hunters Jerkin +1", "DEF":45, "HP":20, "VIT":4, "AGI":4, "Ranged Accuracy":10, "Accuracy":10, "Store TP":8, "Jobs":["rng"]}
Myochin_Domaru1 = {"Name": "Myochin Domaru +1", "DEF":50, "HP":10, "STR":6, "VIT":6, "Accuracy":12, "Meditate Duration":1, "Regen":3, "Jobs":["sam"]}
Ninja_Chainmail1 = {"Name": "Ninja Chainmail +1", "DEF":46, "HP":15, "DEX":5, "VIT":5, "Dual Wield":8, "Accuracy":8, "Jobs":["nin"]}
Drachen_Mail1 = {"Name": "Drachen Mail +1", "DEF":49, "HP":15, "STR":6, "VIT":6, "Attack":7, "Accuracy":10, "Store TP":8, "Jobs":["drg"]}
Evokers_Doublet1 = {"Name": "Evokers Doublet +1", "DEF":35, "MP":45, "BP Delay":-4, "HMP":8, "Pet Accuracy":8, "Pet Ranged Accuracy":8, "Jobs":["smn"]}
Magus_Jubbah1 = {"Name": "Magus Jubbah +1", "DEF":45, "HP":17, "MP":17, "STR":5, "DEX":5, "Blue Magic Skill":15, "HHP":1, "HMP":1, "Accuracy":10, "Dual Wield":3, "Jobs":["blu"]}
Corsairs_Frac1 = {"Name": "Corsairs Frac +1", "DEF":43, "HP":20, "DEX":5, "AGI":16, "Ranged Accuracy":10, "Ranged Attack":5, "Marksmanship Skill":3, "Jobs":["cor"]}
Puppetry_Tobe1 = {"Name": "Puppetry Tobe +1", "DEF":37, "HP":17, "Accuracy":5, "Attack":5, "Martial Arts":2, "Store TP":5, "Jobs":["pup"]}
Dancers_Casaque1 = {"Name": "Dancers Casaque +1", "DEF":39, "HP":25, "STR":5, "DEX":5, "Waltz Potency":15, "Enmity":-2, "Walts Delay":-5, "Jobs":["dnc"]}
Scholars_Gown1 = {"Name": "Scholars Gown +1", "DEF":39, "MP":18, "INT":3, "MND":3, "Dark Arts Skills":15, "HMP":5, "Magic Accuracy":5, "Magic Attack Bonus":5, "Jobs":["sch"]}
Geomancy_Tunic1 = {"Name": "Geomancy Tunic +1", "DEF":40, "MP":35, "Dark Magic Skill":12, "DT":-5, "Magic Accuracy":5, "Jobs":["geo"]}
Runeist_Coat1 = {"Name": "Runeist Coat +1", "DEF":50, "HP":20, "MP":20, "STR":5, "VIT":5, "Resist Elements":10, "Valiance Duration":15, "Vallation":15, "MDT":-5, "Parry Rate":5, "Jobs":["run"]}

#Hands
Fighters_Mufflers1 = {"Name": "Fighters Mufflers +1", "DEF":22, "HP":13, "STR":6, "Shield Skill":15, "Enmity":9, "PDT":-3, "Jobs":["war"]}
Temple_Gloves1 = {"Name": "Temple Gloves +1", "DEF":15, "HP":14, "STR":6, "Subtle Blow":4, "Boost":5.5, "DA":3, "Gear Haste":3, "Jobs":["mnk"]}
Healers_Mitts1 = {"Name": "Healers Mitts +1", "DEF":14, "MP":15, "STR":7, "MND":7, "Healing Magic Skill":15, "Enmity":-4, "Cure Potency":3, "Conserve MP":5, "Jobs":["whm"]}
Wizards_Gloves1 = {"Name": "Wizards Gloves +1", "DEF":13, "MP":17, "INT":3, "CHR":3, "Elemental Magic Skill":15, "Enmity":-2, "Magic Attack Bonus":5, "Conserve MP":5, "Jobs":["blm"]}
Warlocks_Gloves1 = {"Name": "Warlocks Gloves +1", "DEF":17, "MP":17, "DEX":6, "INT":2, "MND":2, "Parrying Skill":15, "DA":3, "Gear Haste":3, "Jobs":["rdm"]}
Rogues_Armlets1 = {"Name": "Rogues Armlets +1", "DEF":16, "HP":10, "DEX":3, "Steal":1, "Treasure Hunter":1, "Gear Haste":3, "Jobs":["thf"]}
Gallant_Gauntlets1 = {"Name": "Gallant Gauntlets +1", "DEF":22, "HP":11, "DEX":6, "VIT":3, "Enmity":2, "MDT":5, "Enemy Crit Rate":-3, "Jobs":["pld"]}
Chaos_Gauntlets1 = {"Name": "Chaos Gauntlets +1", "DEF":20, "HP":11, "MP":11, "STR":6, "DEX":6, "Accuracy":3, "Weapon Bash":10, "Store TP":5, "Gear Haste":5, "Jobs":["drk"]}
Beast_Gloves1 = {"Name": "Beast Gloves +1", "DEF":15, "HP":11, "DEX":5, "CHR":5, "Parrying Skill":10, "Charm":3, "DA":3, "Gear Haste":5, "Jobs":["bst"]}
Choral_Cuffs1 = {"Name": "Choral Cuffs +1", "DEF":18, "HP":14, "VIT":7, "CHR":10, "Singing Skill":10, "Enmity":-1, "Magic Accuracy":3, "Jobs":["brd"]}
Hunters_Bracers1 = {"Name": "Hunters Bracers +1", "DEF":14, "HP":10, "DEX":6, "AGI":6, "Barrage":3, "Shadowbind Duration":15, "Ranged Accuracy":6, "Jobs":["rng"]}
Myochin_Kote1 = {"Name": "Myochin Kote +1", "DEF":21, "HP":15, "STR":7, "DEX":7, "Enmity":2, "Zanshin":3, "Gear Haste":3, "Jobs":["sam"]}
Ninja_Tekko1 = {"Name": "Ninja Tekko +1", "DEF":18, "HP":13, "STR":6, "DEX":6, "Ranged Accuracy":20, "Ranged Attack":20, "Throwing Skill":5, "DA":3, "Gear Haste":3, "Jobs":["nin"]}
Drachen_Finger_Gauntlets1 = {"Name": "Drachen Finger Gauntlets +1", "DEF":19, "HP":11, "STR":5, "DEX":5, "Parrying Skill":12, "DA":3, "Gear Haste":3, "Jobs":["drg"]}
Evokers_Bracers1 = {"Name": "Evokers Bracers +1", "DEF":11, "MP":19, "BP Delay":-1, "Pet DT":-5, "Pet Haste":5, "Jobs":["smn"]}
Magus_Bazubands1 = {"Name": "Magus Bazubands +1", "DEF":17, "MP":20, "STR":3, "INT":3, "Parrying Skill":10, "DA":3, "Gear Haste":3, "Jobs":["blu"]}
Corsairs_Gants1 = {"Name": "Corsairs Gants +1", "DEF":12, "HP":15, "DEX":5, "MND":5, "Evasion":3, "Parrying Skill":5, "DA":3, "Gear Haste":3, "Jobs":["cor"]}
Puppetry_Dastanas1 = {"Name": "Puppetry Dastanas +1", "DEF":13, "HP":18, "STR":5, "AGI":5, "Maneuver Stats":1, "Overload Rate":-5, "DA":3, "Gear Haste":3, "Jobs":["pup"]}
Dancers_Bangles1 = {"Name": "Dancers Bangles +1", "DEF":16, "HP":17, "DEX":4, "AGI":4, "Attack":5, "Step Accuracy":10, "Dual Wield":3, "Gear Haste":3, "Jobs":["dnc"]}
Scholars_Bracers1 = {"Name": "Scholars Bracers +1", "DEF":15, "MP":20, "MND":5, "Spell Interrupt Down":20, "Enmity":-3, "Refresh":1, "HMP":3, "Jobs":["sch"]}
Geomancy_Mitaines1 = {"Name": "Geomancy Mitaines +1", "DEF":15, "MP":16, "INT":3, "MND":4, "Geomancy Skill":15, "Loupan DT":-11, "Conserve MP":3, "Jobs":["geo"]}
Runeist_Mitons1 = {"Name": "Runeist Mitons +1", "DEF":21, "MP":22, "DEX":3, "VIT":3, "Refresh":1, "Gambit Duration":12, "Great Sword Skill":5, "Enmity":3, "Jobs":["run"]}


#Legs
Fighters_Cuisses1 = {"Name": "Fighters Cuisses +1", "DEF":39, "HP":15, "Accuracy":5, "Evasion":5, "Enmity":9, "HHP":2, "PDT":-3, "Jobs":["war"]}
Temple_Hose1 = {"Name": "Temple Hose +1", "DEF":31, "HP":18, "MND":4, "Guarding Skill":15, "Counter":3, "VIT":11, "STR":11, "Jobs":["mnk"]}
Healers_Pantaloons1 = {"Name": "Healers Pantaloons +1", "DEF":28, "MP":30, "VIT":5, "Divine Magic Skill":15, "Enmity":-2, "Magic Accuracy":5, "Cure Cast Time":-3, "Jobs":["whm"]}
Wizards_Tonban1 = {"Name": "Wizards Tonban +1", "DEF":27, "MP":19, "Dark Magic Skill":15, "Enmity":-2, "HMP":1, "Magic Accuracy":5, "Drain Aspir":5, "Jobs":["blm"]}
Warlocks_Tights1 = {"Name": "Warlocks Tights +1", "DEF":33, "MP":54, "MND":5, "Healing Magic Skill":10, "Enhancing Magic Skill":15, "Cure Potency":6, "Jobs":["rdm"]}
Rogues_Culottes1 = {"Name": "Rogues Culottes +1", "DEF":34, "HP":15, "DEX":2, "AGI":4, "Steal":1, "Ranged Accuracy":8, "Ranged Attack":8, "Jobs":["thf"]}
Gallant_Breeches1 = {"Name": "Gallant Breeches +1", "DEF":43, "HP":20, "AGI":4, "Enhancing Magic Skill":10, "Enmity":2, "Shield Mastery":2, "Shield Skill":5, "Jobs":["pld"]}
Chaos_Flanchard1 = {"Name": "Chaos Flanchard +1", "DEF":38, "HP":15, "MP":15, "DEX":5, "INT":10, "Evasion":5, "Parrying Skill":15, "Drain Aspir":5, "Jobs":["drk"]}
Beast_Trousers1 = {"Name": "Beast Trousers +1", "DEF":34, "HP":15, "STR":6, "CHR":6, "Charm":6, "Killer Effects":1, "Charm":6, "Pet DA":4, "Pet Crit Rate":4, "Gear Haste":5, "Jobs":["bst"]}
Choral_Cannions1 = {"Name": "Choral Cannions +1", "DEF":31, "HP":12, "STR":8, "DEX":8, "Wind Skill":8, "Enmity":-2, "Song Recast":-3, "Earth Magic Accuracy":5, "Jobs":["brd"]}
Hunters_Braccae1 = {"Name": "Hunters Braccae +1", "DEF":32, "HP":15, "AGI":5, "MND":5, "Enmity":-3, "Sharpshot":10, "DEX":11, "AGI":11, "Jobs":["rng"]}
Myochin_Haidate1 = {"Name": "Myochin Haidate +1", "DEF":40, "HP":15, "STR":5, "VIT":5, "Parrying Skill":10, "Store TP":9, "Gear Haste":5, "Jobs":["sam"]}
Ninja_Hakame1 = {"Name": "Ninja Hakame +1", "DEF":31, "Accuracy":5, "Ranged Accuracy":10, "Evasion":5, "Tool Expertise":3, "Jobs":["nin"]}
Drachen_Brais1 = {"Name": "Drachen Brais +1", "DEF":32, "HP":15, "Accuracy":9, "Ancient Circle":2, "Gear Haste":3, "Pet Accuracy":15, "Pet Ranged Accuracy":15, "Jobs":["drg"]}
Evokers_Spats1 = {"Name": "Evokers Spats +1", "DEF":25, "MP":22, "Enmity":-3, "Avatar Accuracy":10, "Pet Attack":3, "Pet Ranged Attack":3, "Pet DA":3, "Jobs":["smn"]}
Magus_Shalwar1 = {"Name": "Magus Shalwar +1", "DEF":34, "HP":25, "DEX":5, "VIT":5, "AGI":5, "Spell Interrupt Down":12, "Refresh":1, "Regen":3, "Jobs":["blu"]}
Corsairs_Culottes1 = {"Name": "Corsairs Culottes +1", "DEF":29, "HP":25, "INT":5, "AGI":5, "Enmity":-4, "Accuracy":6, "Dual Wield":3, "Jobs":["cor"]}
Puppetry_Churidars1 = {"Name": "Puppetry Churidars +1", "DEF":26, "HP":16, "DEX":5, "CHR":5, "Automaton Cure Potency":5, "Automaton DA":4, "Automaton Crit Rate":4, "Gear Haste":3, "Jobs":["pup"]}
Dancers_Tights1 = {"Name": "Dancers Tights +1", "DEF":29, "HP":15, "VIT":5, "CHR":5, "Accuracy":5, "Attack":5, "Enmity":-1, "STR":11, "DEX":11, "Jobs":["dnc"]}
Scholars_Pants1 = {"Name": "Scholars Pants +1", "DEF":28, "MP":25, "VIT":3, "MND":3, "Enmity":-2, "Light Arts Skills":15, "Conserve MP":5, "Cure Potency":6, "Jobs":["sch"]}
Geomancy_Pants1 = {"Name": "Geomancy Pants +1", "DEF":30, "MP":20, "FC":10, "Spell Interrupt Down":15, "INT":11, "MND":11, "Jobs":["geo"]}
Runeist_Trousers1 = {"Name": "Runeist Trousers +1", "DEF":40, "HP":15, "MP":15, "STR":7, "Enmity":5, "DT":-3, "VIT":11, "MND":11, "Jobs":["run"]}

#Feet
Fighters_Calligae1 = {"Name": "Fighters Calligae +1", "HP":19, "VIT":3, "AGI":3, "DA":4, "Enmity":1, "Store TP":6, "Jobs":["war"]}
Temple_Gaiters1 = {"Name": "Temple Gaiters +1", "DEF":15, "HP":12, "DEX":5, "MND":5, "Evasion":10, "Dodge":10, "Kick Rate":5, "Gear Haste":3, "Jobs":["mnk"]}
Healers_Duckbills1 = {"Name": "Healers Duckbills +1", "DEF":12, "MP":54, "AGI":5, "INT":5, "Spell Interrupt Rate":-25, "HMP":4, "Jobs":["whm"]}
Wizards_Sabots1 = {"Name": "Wizards Sabots +1", "DEF":11, "MP":54, "AGI":5, "MND":5, "Spell Interrupt Rate":-20, "HMP":4, "Jobs":["blm"]}
Warlocks_Boots1 = {"Name": "Warlocks Boots +1", "DEF":15, "MP":55, "AGI":3, "INT":3, "MND":3, "Shield Skill":10, "HMP":5,  "Jobs":["rdm"]}
Rogues_Poulaines1 = {"Name": "Rogues Poulaines +1", "DEF":15, "DEX":3, "Ranged Accuracy":5, "Steal":2, "DA":3, "Gear Haste":3, "Jobs":["thf"]}
Gallant_Leggings1 = {"Name": "Gallant Leggings +1", "DEF":19, "HP":20, "CHR":5, "Shield Skill":12, "BDT":-5, "Magic Defense Bonus":3, "Jobs":["pld"]}
Chaos_Sollerets1 = {"Name": "Chaos Sollerets +1", "DEF":17, "HP":15, "MP":15, "STR":5, "MND":5, "DA":3, "Gear Haste":3, "Jobs":["drk"]}
Beast_Gaiters1 = {"Name": "Beast Gaiters +1", "DEF":14, "HP":11, "AGI":5, "CHR":5, "Charm":2, "Reward":11, "Pet Regen":3, "Gear Haste":5, "Jobs":["bst"]}
Choral_Slippers1 = {"Name": "Choral Slippers +1", "DEF":14, "HP":10, "DEX":5, "AGI":5, "Evasion":5, "HHP":5, "HMP":7,  "Jobs":["brd"]}
Hunters_Socks1 = {"Name": "Hunters Socks +1", "DEX":16, "DEX":16, "AGI":6, "Evasion":5, "Scavange":5, "DA":3, "Gear Haste":5, "Jobs":["rng"]}
Myochin_SuneAte1 = {"Name": "Myochin Sun-Ate +1", "DEF":18, "HP":20, "Attack":8, "Enmity":5, "Zanshin":5, "DA":3, "Gear Haste":3, "Jobs":["sam"]}
Ninja_Kyahan1 = {"Name": "Ninja Kyahan +1", "DEF":15, "HP":12, "AGI":6, "INT":6, "Magic Attack Bonus":10, "Ninjutsu Skill":5, "Jobs":["nin"]}
Drachen_Greaves1 = {"Name": "Drachen Greaves +1", "DEF":16, "HP":12, "DEX":5, "AGI":5, "Evasion":10, "Jump":15, "Pet Regen":3, "Gear Haste":3, "Jobs":["drg"]}
Evokers_Pigaches1 = {"Name": "Evokers Pigaches +1", "DEF":10, "MP":25, "Avatar Perpetuation Cost":-1, "Pet Regen":3, "Elemental Siphon":5, "Jobs":["smn"]}
Magus_Charuqs1 = {"Name": "Magus Charuqs +1", "DEF":14, "HP":18, "MP":18, "Accuracy":3, "Evasion Skill":10, "Enmity":-5, "Magic Attack Bonus":10, "Blue Magic Skill":5, "Jobs":["blu"]}
Corsairs_Bottes1 = {"Name": "Corsairs Bottes +1", "DEF":12, "HP":15, "STR":5, "AGI":5, "Ranged Accuracy":4, "Accuracy":4, "Rapid Shot":5, "Snapshot":3, "Jobs":["cor"]}
Puppetry_Babouches1 = {"Name": "Puppetry Babouches +1", "DEF":12, "HP":19, "STR":5, "Accuracy":5, "Evasion":5, "Pet Regen":3, "Repair Potency":3, "Jobs":["pup"]}
Dancers_Toe_Shoes1 = {"Name": "Dancers Toe Shoes +1", "DEF":15, "HP":12, "STR":3, "AGI":3, "Attack":5, "Evasion":5, "Jig Duration":25, "DA":3, "Gear Haste":3, "Jobs":["dnc"]}
Scholars_Loafers1 = {"Name": "Scholars Loafers +1", "DEF":11, "MP":20, "AGI":3, "INT":3, "Enmity":-2, "Grimoire FC":5, "Magic Accuracy":5, "Drain Aspir":5, "Jobs":["sch"]}
Geomancy_Sandals1 = {"Name": "Geomancy Sandals +1", "DEF":12, "MP":54, "AGI":5, "CHR":5, "Movement Speed":12, "HMP":5, "Jobs":["geo"]}
Runeist_Bottes1 = {"Name": "Runeist Bottes +1", "DEF":18, "MP":18, "VIT":6, "Magic Defense Bonus":2, "Pflug":10, "BDT":-3, "Enmity":3, "Jobs":["run"]}